image_width: 255
image_height: 255

fonts_directory: "fonts"
output_directory: "output"


characters: ['ق', 'ھ', 'غ', 'ص']
font_sizes: [10, 20, 30, 50]
img_background_colors: [0, 100, 150]
character_colors: [200, 255]
character_positions: [[110, 50]] # xy, relative to the top left of image
